CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255),
    phone VARCHAR2(30),
    status VARCHAR2(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);
CREATE TABLE merchants (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    upi_vpa VARCHAR2(255),
    settlement_account VARCHAR2(255),
    status VARCHAR2(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_reference_id VARCHAR2(64) UNIQUE NOT NULL,
    user_id NUMBER,
    merchant_id NUMBER,
    payment_method VARCHAR2(30),
    amount NUMBER(18,2) NOT NULL,
    status VARCHAR2(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id NUMBER,
    user_id NUMBER,
    payment_reference_id VARCHAR2(64),
    status VARCHAR2(30),
    audit_log VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE transaction_audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id NUMBER,
    previous_status VARCHAR2(30),
    new_status VARCHAR2(30),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changed_by VARCHAR2(100)
);
CREATE TABLE webhook_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR2(100),
    event_type VARCHAR2(100),
    payload CLOB,
    verified NUMBER(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE refunds (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id NUMBER,
    amount NUMBER(18,2),
    status VARCHAR2(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE settlements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id NUMBER,
    settlement_reference VARCHAR2(100),
    amount NUMBER(18,2),
    status VARCHAR2(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_payment_ref ON transactions(payment_reference_id);
CREATE INDEX idx_payments_merchant_id ON payments(merchant_id);
CREATE INDEX idx_payments_status ON payments(status);
